### ISSUE TITLE
Stack trace window appears when starting timer with non-empty input file

### ISSUE THREAD

**Issue by carltonwhitehead** [caeos/coner-drs#43]
```
java.lang.IllegalStateException: Not on FX application thread; currentThread = pool-4-thread-1
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.Parent$2.onProposedChange(Parent.java:367)
	at com.sun.javafx.collections.VetoableListDecorator.add(VetoableListDecorator.java:206)
	at tornadofx.FXKt.addChildIfPossible(FX.kt:615)
	at tornadofx.FXKt.addChildIfPossible$default(FX.kt:496)
	at tornadofx.LayoutsKt.flowpane(Layouts.kt:456)
	at org.coner.drs.ui.runevent.RunEventTableView$root$1$1$1$10$1.invoke(RunEventTableView.kt:36)
	at org.coner.drs.ui.runevent.RunEventTableView$root$1$1$1$10$1.invoke(RunEventTableView.kt:12)
	at tornadofx.SmartTableCell.updateItem(TableView.kt:100)
	at javafx.scene.control.TableCell.updateItem(TableCell.java:663)
	at javafx.scene.control.TableCell.indexChanged(TableCell.java:468)
	at javafx.scene.control.IndexedCell.updateIndex(IndexedCell.java:116)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.updateCells(TableRowSkinBase.java:533)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.checkState(TableRowSkinBase.java:634)
	at com.sun.javafx.scene.control.skin.TableRowSkinBase.computePrefHeight(TableRowSkinBase.java:571)
	at javafx.scene.control.Control.computePrefHeight(Control.java:547)
	at javafx.scene.Parent.prefHeight(Parent.java:935)
	at javafx.scene.layout.Region.prefHeight(Region.java:1435)
	at com.sun.javafx.scene.control.skin.VirtualFlow.resizeCellSize(VirtualFlow.java:1947)
	at com.sun.javafx.scene.control.skin.VirtualFlow.addLeadingCells(VirtualFlow.java:1247)
	at com.sun.javafx.scene.control.skin.VirtualFlow.layoutChildren(VirtualFlow.java:1194)
	at com.sun.javafx.scene.control.skin.VirtualFlow.setCellCount(VirtualFlow.java:231)
	at com.sun.javafx.scene.control.skin.TableViewSkinBase.updateRowCount(TableViewSkinBase.java:567)
	at com.sun.javafx.scene.control.skin.VirtualContainerBase.lambda$new$0(VirtualContainerBase.java:54)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.ControlUtils.lambda$scrollToIndex$0(ControlUtils.java:46)
	at com.sun.javafx.scene.control.skin.Utils.executeOnceWhenPropertyIsNonNull(Utils.java:779)
	at javafx.scene.control.ControlUtils.scrollToIndex(ControlUtils.java:45)
	at javafx.scene.control.TableView.scrollTo(TableView.java:1328)
	at org.coner.drs.ui.runevent.RunEventTableView$root$1$1$1$12.invoke(RunEventTableView.kt:137)
	at org.coner.drs.ui.runevent.RunEventTableView$root$1$1$1$12.invoke(RunEventTableView.kt:12)
	at tornadofx.LibKt$onChange$$inlined$apply$lambda$7.onChanged(Lib.kt:268)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.transformation.SortedList.sourceChanged(SortedList.java:111)
	at javafx.collections.transformation.TransformationList.lambda$getListener$0(TransformationList.java:106)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.coner.drs.domain.service.RunService.addNextTimeSync(RunService.kt:77)
	at org.coner.drs.domain.service.RunService.access$addNextTimeSync(RunService.kt:15)
	at org.coner.drs.domain.service.RunService$addNextTime$1.invoke(RunService.kt:69)
	at org.coner.drs.domain.service.RunService$addNextTime$1.invoke(RunService.kt:15)
	at org.coner.drs.domain.service.DomainServiceController$scheduleCompletable$1$1.run(DomainServiceController.kt:23)
	at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.internal.operators.completable.CompletableObserveOn.subscribeActual(CompletableObserveOn.java:34)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by carltonwhitehead** [comment]
Only seems to occur when time insertion occurs beyond the last run. Either way, not acceptable, since this could conceivably occur with timing equipment if the worker gets behind for a moment.
